# -*- coding: utf-8 -*-
"""dashboard.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yFLpN5QqAr86J1IbM3xFPc6WSW46WHHP
"""

pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py

! wget -q -O - ipv4.icanhazip.com

! streamlit run app.py & npx localtunnel --port 8501

# Nama file: dashboard.py

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# Membaca dataset
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Dataset/all_data.csv')

# Menampilkan judul
st.title('Dashboard Sederhana')

# Menampilkan data
st.write('Data:')
st.write(df.head())

# Statistik deskriptif
st.write('Statistik Deskriptif:')
st.write(df.describe())

# Menampilkan grafik
st.write('Grafik Histogram:')
numeric_columns = df.select_dtypes(include=['float64', 'int64']).columns.tolist()

# Pilih kolom untuk histogram
column = st.selectbox('Pilih kolom untuk histogram:', numeric_columns)

fig, ax = plt.subplots()
ax.hist(df[column].dropna(), bins=20, edgecolor='black')
ax.set_title(f'Histogram dari {column}')
ax.set_xlabel(column)
ax.set_ylabel('Frekuensi')
st.pyplot(fig)

